Sprint3
ClevertecFrontendLab/Belski-Anton pull request #3
Opened 2024-03-04 17:25 UTC by Belski-Anton

2024-03-04 18:21 UTC, Ivan6813 requested changes

2024-03-04 18:21 UTC, Ivan6813 commented on src/api/auth-api.ts
Между аватаркой и именем расстояние должно быть меньше, сверься с макетом
![image](https://github.com/ClevertecFrontendLab/Belski-Anton/assets/79784960/8e5f3d41-5b9a-4615-ae73-15bd6da2d956)

2024-03-04 20:18 UTC, Xaky0105 commented on src/api/auth-api.ts
>                  url: '/auth/check-email',
Это нужно вынести в константы

2024-03-04 20:23 UTC, Xaky0105 commented on src/api/auth-api.ts
> +                url: '/auth/confirm-email',
все урлы должны быть вынесены в константы

2024-03-04 20:23 UTC, Xaky0105 commented on src/components/form/login-form/login-form.tsx
> +        const googleAuthUrl = `${BASE_API_URL}/auth/google`;
и здесь тоже

2024-03-04 20:24 UTC, Xaky0105 commented on src/components/popup/wrong-modal/modal-wrong.jsx
> +                status='500'
все статусы тоже в константы

2024-03-04 20:25 UTC, Xaky0105 commented on src/index.tsx
> +                        <Route path='main' element={<MainPage />} />
пути тоже в константы

2024-03-04 20:26 UTC, Xaky0105 commented on cypress/e2e/spec.cy.ts
> +                body: { message: 'test321', rating: 3 },
зачем был отредактирован тест?

2024-03-04 20:29 UTC, Xaky0105 requested changes
Слишком большой отступ, сверьтесь с макетом
![Screenshot_13](https://github.com/ClevertecFrontendLab/Belski-Anton/assets/81919274/c6898e4e-c720-43ca-9c0a-6f270738a48b)

2024-03-05 15:47 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**empty-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Belski-Anton/1709653676/empty-review-list.png)
***
**expand-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Belski-Anton/1709653676/expand-review-list.png)
***
**get-feedback-error.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Belski-Anton/1709653676/get-feedback-error.png)
***
**more-than-4-reviews.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Belski-Anton/1709653676/more-than-4-reviews.png)
***
**one-review.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Belski-Anton/1709653676/one-review.png)
***
**review-modal.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Belski-Anton/1709653676/review-modal.png)
***
**reviews-not-saved-modal.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Belski-Anton/1709653676/reviews-not-saved-modal.png)
***
**updated-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Belski-Anton/1709653676/updated-review-list.png)

2024-03-05 15:52 UTC, Ivan6813 commented on cypress/e2e/spec.cy.ts
> +                body: [{ message: 'test321', rating: 3 }],
В модалке успеха неверный текст и так же в модалке написания отзыва кнопка должна была задизейблена если не проставлен рейтинг и поле ввода пустое
![image](https://github.com/ClevertecFrontendLab/Belski-Anton/assets/79784960/e481f8ab-8c14-4402-a02a-604041c993e4)

2024-03-05 15:56 UTC, Xaky0105 approved these changes

2024-03-05 16:30 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**empty-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Belski-Anton/1709656232/empty-review-list.png)
***
**expand-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Belski-Anton/1709656232/expand-review-list.png)
***
**get-feedback-error.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Belski-Anton/1709656232/get-feedback-error.png)
***
**more-than-4-reviews.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Belski-Anton/1709656232/more-than-4-reviews.png)
***
**one-review.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Belski-Anton/1709656232/one-review.png)
***
**review-modal.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Belski-Anton/1709656232/review-modal.png)
***
**reviews-not-saved-modal.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Belski-Anton/1709656232/reviews-not-saved-modal.png)
***
**updated-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Belski-Anton/1709656232/updated-review-list.png)

2024-03-05 16:46 UTC, merged